server:
  port: 8081
spring:
  data:
    redis:
      host: localhost
      port: 6379
  r2dbc:
    url: r2dbc:h2:mem:///blog_search_db
    username: sa
    password:
logging:
  level:
    io:
      r2dbc:
        h2: TRACE