DROP TABLE IF EXISTS keyword;
DROP TABLE IF EXISTS keyword_history;

CREATE TABLE keyword (
id bigint generated by default as identity,
keyword VARCHAR(255) NOT NULL ,
PRIMARY KEY (id),
UNIQUE (keyword)
);

CREATE TABLE keyword_history (
    id bigint generated by default as identity,
    keyword_id bigint NOT NULL ,
    searching_date timestamp,
    PRIMARY KEY (id)
);

INSERT INTO keyword (keyword) values ('계란찜 만들기');
INSERT INTO keyword (keyword) values ('자동차');
INSERT INTO keyword (keyword) values ('통영숙소');
INSERT INTO keyword (keyword) values ('국내 벛꽃여행지 추천');
INSERT INTO keyword (keyword) values ('정자역 맛집 추천');

INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '계란찜 만들기'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '계란찜 만들기'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '자동차'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '자동차'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '자동차'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '자동차'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '통영숙소'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '통영숙소'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '통영숙소'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '통영숙소'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '통영숙소'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '국내 벛꽃여행지 추천'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '국내 벛꽃여행지 추천'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '국내 벛꽃여행지 추천'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '국내 벛꽃여행지 추천'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '국내 벛꽃여행지 추천'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '국내 벛꽃여행지 추천'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '국내 벛꽃여행지 추천'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '국내 벛꽃여행지 추천'), now());
INSERT INTO keyword_history (keyword_id, searching_date) values ((select id from keyword where keyword = '정자역 맛집 추천'), now());
