server:
  port: 8080
external-search-api:
  kakao:
    rest-key: KakaoAK 6b3eb427d4d89af338da207535944b2a
    base-url: https://dapi.kakao.com/v2/search
    search-path:
      blog: /blog
  naver:
    id: qu96nxpopr9CIHFXQgBF
    secret: jjNIeWwWFc
    base-url: https://openapi.naver.com/v1/search
    search-path:
      blog: /blog.json
api:
  base-url: http://localhost:8081/api
  path:
    keyword: /keyword
logging:
  level:
    root: debug